### ISSUE TITLE
podAnnotations clobbered

### ISSUE THREAD

**Issue by dvarrazzo** [makezbs/helm-charts#13]
https://github.com/makezbs/helm-charts/blob/7a09493e1afe2b00b15a921c0456fed1e3134dc0/charts/query-exporter/templates/deployment.yaml#L21-L28

`podAnnotations` cannot work, because it's always overwritten by `checksum/config`

Adding:

```yaml
podAnnotations:
  prometheus.io/scrape: "true"
```

results in:

```yaml
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: query-exporter
        app.kubernetes.io/instance: query-exporter
      annotations:
        checksum/config: 4b0ec09fa75fdac160f2ea015f6f1e78fcc79c2fb97dc6dbbeb2cb852377483c
```

but the annotation is not received by k8s.
